language: node_js
node_js:
  - '10'

# Cache npm packages
cache: npm

# Default for install is npm ci w/ package-lock.json
# install

# Default for script lifecycle is npm test
# script

# Release with Semantic after tests pass
deploy:
  provider: script
  # Prevent Travis from resetting working directory after build
  skip_cleanup: true
  script: npx semantic-release
  on:
    branch: master
